irqbalance: Fix QA error when sysvinit is used
irqbalance: correct to install /etc/default for sysvinit

1.This commit uses option --with-pkgconfdir for sysvinit to correct to install /etc/default
  Without this fix, there will show do_package QA Issue when sysvinit is used
  ERROR: irqbalance-1.9.4+git-r0 do_package: QA Issue: irqbalance: Files/directories were installed but not shipped in any package:
    /usr/etc
    /usr/etc/default
    /usr/etc/default/irqbalance.env

  Previous PACKAGECONFIG[systemd] only works when systemd is used. So making this patch to fix it.

2.Merge DEPENDS for systemd into PACKAGECONFIG[systemd]

Signed-off-by: Liu Yiding <liuyd.fnst@fujitsu.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>